create sequence hibernate_sequence start 1 increment 1;
create table crop (id int8 not null, amount int4 not null, cost float8 not null, price float8 not null, primary key (id));
create table input_data (id int8 not null, budget float8 not null, primary key (id));
create table solution (id int8 not null, primary key (id));
create table solution_crops (solution_id int8 not null, crops_id int8 not null);
alter table if exists solution_crops add constraint UK_40gs342wu0kv3o4o82y1aiuot unique (crops_id);
alter table if exists solution_crops add constraint FKgf9hvx2nlsn4ojf89ngg975dn foreign key (crops_id) references crop;
alter table if exists solution_crops add constraint FKdoc1361k0hryxp6r5tis2dbw5 foreign key (solution_id) references solution;
create sequence hibernate_sequence start 1 increment 1;
create table crop (id int8 not null, amount int4 not null, cost float8 not null, price float8 not null, primary key (id));
create table input_data (id int8 not null, budget float8 not null, primary key (id));
create table solution (id int8 not null, primary key (id));
create table solution_crops (solution_id int8 not null, crops_id int8 not null);
alter table if exists solution_crops add constraint UK_40gs342wu0kv3o4o82y1aiuot unique (crops_id);
alter table if exists solution_crops add constraint FKgf9hvx2nlsn4ojf89ngg975dn foreign key (crops_id) references crop;
alter table if exists solution_crops add constraint FKdoc1361k0hryxp6r5tis2dbw5 foreign key (solution_id) references solution;
create sequence hibernate_sequence start 1 increment 1;
create table crop (id int8 not null, amount int4 not null, cost float8 not null, price float8 not null, primary key (id));
create table input_data (id int8 not null, budget float8 not null, primary key (id));
create table solution (id int8 not null, primary key (id));
create table solution_crops (solution_id int8 not null, crops_id int8 not null);
alter table if exists solution_crops add constraint UK_40gs342wu0kv3o4o82y1aiuot unique (crops_id);
alter table if exists solution_crops add constraint FKgf9hvx2nlsn4ojf89ngg975dn foreign key (crops_id) references crop;
alter table if exists solution_crops add constraint FKdoc1361k0hryxp6r5tis2dbw5 foreign key (solution_id) references solution;
create sequence hibernate_sequence start 1 increment 1;
create table crop (id int8 not null, amount int4 not null, cost float8 not null, price float8 not null, primary key (id));
create table input_data (id int8 not null, budget float8 not null, primary key (id));
create table solution (id int8 not null, primary key (id));
create table solution_crops (solution_id int8 not null, crops_id int8 not null);
alter table if exists solution_crops add constraint UK_40gs342wu0kv3o4o82y1aiuot unique (crops_id);
alter table if exists solution_crops add constraint FKgf9hvx2nlsn4ojf89ngg975dn foreign key (crops_id) references crop;
alter table if exists solution_crops add constraint FKdoc1361k0hryxp6r5tis2dbw5 foreign key (solution_id) references solution;
create sequence hibernate_sequence start 1 increment 1;
create table crop (id int8 not null, amount int4 not null, cost float8 not null, price float8 not null, primary key (id));
create table input_data (id int8 not null, budget float8 not null, primary key (id));
create table solution (id int8 not null, primary key (id));
create table solution_crops (solution_id int8 not null, crops_id int8 not null);
alter table if exists solution_crops add constraint UK_40gs342wu0kv3o4o82y1aiuot unique (crops_id);
alter table if exists solution_crops add constraint FKgf9hvx2nlsn4ojf89ngg975dn foreign key (crops_id) references crop;
alter table if exists solution_crops add constraint FKdoc1361k0hryxp6r5tis2dbw5 foreign key (solution_id) references solution;
