services:
  postgres:
    image: postgres
    container_name: po-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PO
    hostname: postgres
    ports:
      - 15432:5432
    volumes:
      - /usr/postgres/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: po-pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@po.com.br
      PGADMIN_DEFAULT_PASSWORD: po123
    ports:
      - 16543:80
    depends_on:
      - postgres
    volumes:
      - /usr/pgadmin
    restart: unless-stopped